// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicketsDetalles.DAL;

#nullable disable

namespace TicketsDetalles.Migrations
{
    [DbContext(typeof(DetalleContext))]
    partial class DetalleContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.7");

            modelBuilder.Entity("TicketsDetalles.Models.TicketsDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Emisor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TicktetId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Detalle");
                });
#pragma warning restore 612, 618
        }
    }
}
